### ISSUE TITLE
New Release should be uploaded

### ISSUE THREAD

**Issue by Bolt23** [ntrteam/ntrboot_flasher#82]
As there have been many commits since latest release and you have updated the Flashcart Core, don’t you think it will be a nice idea to release 0.3.2? I mean many unsupported Flashcart are now supported!

**Comment by Bolt23** [comment]
Well here it is 
[ntrboot_flasherARM.zip](https://github.com/ntrteam/ntrboot_flasher/files/1659731/ntrboot_flasherARM.zip) v0.3.2 (I compiled it :D 🥇 )

**Comment by kitling** [comment]
okay, so, look. there's stuff that we're in the middle of. We may release a pre-release or something soon, but I don't feel comfortable with making a full release atm.

**Comment by Bolt23** [comment]
@kitling Okay mate! As you say, but do you have any update on my R4i SDHC (ndsiLL.com) BLUE (colour) 1.4? I get the norErase4k error, though I submitted the log their at flashcart_core issues. I will be highly obliged and honoured too if you help me out with that..... :D

**Comment by kitling** [comment]
No, I have not ignored/muted you. I just haven't been paying much attention over here in general.

The flashcart issue should stay open. Just because nobody is actively working on it doesn't mean the cart doesn't exist.
