### ISSUE TITLE
Is the M3i Zero compatible with ntrboot_flasher

### ISSUE THREAD

**Issue by Gladuin** [ntrteam/ntrboot_flasher#86]
I found out that I had that one laying around and saw that it was reverse engineerd [here](https://github.com/ntrteam/docs/blob/master/M3iZero-GMPZ003.md) and wondered if it would be compatible with this. It is the non GMP-Z003 version sadly

**Comment by HandsomeMatt** [comment]
Only the GMP-Z003 would be compatible as it has no encryption. My repo has
the code and documentation that would make it possible to integrate into
flashcart_core.

**Comment by Squirrel61** [comment]
If it's not too much work, I would greatly appreciate that, since I have a GMP-Z003 lying around here.

**Comment by jason0597** [comment]
this is more of a [flashcart_core](https://github.com/ntrteam/flashcart_core) issue, not an ntrboot_flasher issue

**Comment by handsomematt** [comment]
https://github.com/handsomematt/gmp-z003/tree/master/tools/z003_ntrboot

compile yourself - compatability is difficult, has to be GMP-Z003 and not on 4.5
